# Generated by Django 5.2.1 on 2025-05-18 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='talleres/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='vehiculos/')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='carritoapp.taller')),
            ],
        ),
    ]
